### ISSUE TITLE
Rubocop?

### ISSUE THREAD

**Issue by will-in-wi** [capistrano/capistrano#1591]
Is there any interest in implementing a Rubocop ruleset for Capistrano? It might improve the consistency of PRs and such. I'm happy to take a first crack at it, but I wanted to check first.

Thanks!

**Comment by mattbrictson** [comment]
I am a huge fan of RuboCop for new projects, but it gets a little tricky for existing ones. I suspect there will be many violations that we will have to ignore, or someone will have to do the tedious work of correcting them. If you want to take a crack at it, then by all means!

For Capistrano, we already have RuboCop included, but we're only running the lint checks at the moment (see .travis.yml and Rakefile).

In terms of the ruleset, I suppose we should look at the existing code to see what are the most common conventions, and go with that.

My personal preference is for hash rockets (controversial, I know) and double-quoted strings, but otherwise the RuboCop defaults. Here's my typical RuboCop config:

```yaml
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 1.9
  Exclude:
    - "*.gemspec"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true
```

But, like I said, it probably makes sense to tweak the rules based on the patterns being used by the existing codebase, and not based on personal preference, unless those preferences are very strongly held (mine are not).
